package com.company.avtoelon.enums;

public enum AdminStatus {

    BLOCK_USER, REMOVE_PRODUCT, ADD_CATEGORY, EDIT_CATEGORY, ADD_ADMIN, SEND_MESSAGE,
    SEND_CATEGORY_NAME, REMOVE_CATEGORY, RENAME_CATEGORY, BACK,
    SHOW_CATEGORY, CONFIRM_PRODUCTS


}
