package com.company.avtoelon.enums;

public enum Region {
    TOSHKENT, BUXORO, SIRDARYO, NAMANGAN, JIZZAX, ANDIJON, FARGONA,
    NAVOIY, QASHQADARYO, SURXANDARYO, SAMARQAND, QORAQALPAGISTON, XORAZM, ALL
}
