package com.company.avtoelon.enums;

public enum UserStatus {

    SEND_AD_NAME, SEND_PRODUCT_PRICE, IS_NEGOTIABLE, SEND_PRODUCT_INFO, SEND_CONTACT_INFO, SEND_PHOTO,
    CONFIRM_PRODUCT, SHOW_FAVORITES, SEND_LOCATION,
    SHOW_MY_PRODUCTS,
}
